name: railway

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'


jobs:
  railway:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup railway cli
        run: |
          curl -fsSL https://railway.app/install.sh | sh

      - run: |
          rm README.md
          downloadUrl=`curl https://api.github.com/repos/cloudreve/Cloudreve/releases/latest | grep -o 'https://github.com/cloudreve/Cloudreve/releases/download.*linux_amd64.tar.gz'`
          wget -q -O cr.tar.gz $downloadUrl
          tar -xvf cr.tar.gz
          mv cloudreve cr         
          echo "${{ secrets.CONFIG }}" > config.ini
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway up
          
          
    
          
          
          
          
          
