name: railway

on:
  push:
  workflow_dispatch:
  schedule:
//    - cron: '0 21 * * *'


jobs:
  railway:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup railway cli
        run: |
          curl -fsSL https://railway.app/install.sh | sh

      - run: |
          wget -q -O cr.tar.gz https://github.com/cloudreve/Cloudreve/releases/download/3.5.3/cloudreve_3.5.3_linux_amd64.tar.gz
          tar -xvf cr.tar.gz
          mv cloudreve cr         
          echo "${{ secrets.CONFIG }}" > config.ini
          cat /home/runner/work/_temp/*.sh
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway up
          
          
    
          
          
          
          
          
