name: test


on:
  push:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: run
        id: get_time
        run: |
          t1=`curl https://api.github.com/repos/cloudreve/Cloudreve/releases/latest | jq .created_at` # 获取更新时间
          t1=${t1:1:10}
          t2=`date '+%Y-%m-%d'` # 获取今日
          echo "::set-output name=T1::$t1"
          echo "::set-output name=T2::$t2"
      - name: testoutput
        if: steps.get_time.outputs.T1==steps.get_time.outputs.T2
        run:  |
          echo '${{ steps.get_time.outputs.T1 }}'
          echo '${{ steps.get_time.outputs.T2 }}'
